### ISSUE TITLE
Provide favicon for the Project

### ISSUE THREAD

**Issue by andriannus** [tunaiku/amar-ui-web#6]
I see that the `favicon` used is the property of Gatsby.js. Can we have our own `favicon`?

**Comment by dkk94** [comment]
Completely agree that we should have our own logo instead of Gatsby's default one. I think to go forward with this idea, we can use our company's proprietary logo first for the time being while waiting for the completion of our Design System's branding (which I assume the new logo will be included as well). What do you think about this idea? @andriannus @Christian-007

**Comment by andriannus** [comment]
I think that's a good idea 👍

**Comment by dkk94** [comment]
Ok, let's go ahead and move forward with this idea.

**Comment by dkk94** [comment]
This issue has been resolved in PR #12. Closing.
